name: GitHub Actions Demo
on [push, check_run]
jobs:
  Null-Work:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - run: pwd
      - run ls -ali
      - df -BM
      - run: ls -ali /
