name: GitHub Actions Demo
on: [push, check_run]
jobs:
  Null-Work:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls -ali
      - run: df -BM
      - run: ls -ali /
      - run: env
      - run: echo ${{ github.workspace }}
