name: GitHub Actions Demo
on: [push, check_run]
jobs:
  Crossplatform-Work:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: pwd
      - run: ls
      - run: env
      - run: df
      - run: ls /
      - run: ps
  Linux-Work:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: pwd
      - run: ls -ali
      - run: df -BM
      - run: ls -ali /
      - run: env
      - run: ps -ef
  Windows-Work:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
  Macos-Work:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: ls -ali /
      - run: ps -ef
